[package]
name = "serigraph"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.2"
anyhow = "1"
clap = { version = "3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"
log = "0.4.17"